image: node:12.18.3
stages:
  - build
  - deploy

build:
  variables:
    NEXT_PUBLIC_BACKEND_URL: https://bixindex-backend-local.herokuapp.com/
  cache:
    key:
      files:
        - yarn.lock
    paths:
      # No need for the yarn cache
      # - .yarn-cache
      - node_modules/
  before_script:
    - |
      # Utils
      function section() {
        local section_name=$1
        local header=$2
        shift 2
        echo -e "section_start:$(date +%s):${section_name}\r\e[0K${header}"
        "$@"
        echo -e "section_end:$(date +%s):${section_name}\r\e[0K"
      }
    - section yarn_install "Yarn Install" yarn install --frozen-lockfile
  stage: build
  script:
    - yarn build

deploy:dev:
  stage: deploy
  extends:
    - .deploy
    - .dev_vars

deploy:staging:
  stage: deploy
  extends:
    - .deploy
    - .staging_vars

deploy:prod:
  stage: deploy
  extends:
    - .deploy
    - .prod_vars

.deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == $BRANCH_TARGET
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  script:
    - mkdir .vercel
    - echo $DOT_VERCEL} > .vercel/project.json
    - cp vercel.json .vercel/vercel.ci.json
    - DEPLOYMENT_URL=$(yarn -s vercel --scope "${VERCEL_SCOPE}" --token "${VERCEL_TOKEN}" --local-config .vercel/vercel.ci.json)
    - yarn -s vercel --scope "${VERCEL_SCOPE}" --token "${VERCEL_TOKEN} alias "${DEPLOYMENT_URL}" "${VERCEL_ALIAS}"

.dev_vars:
  variables:
    VERCEL_SCOPE: $DEV_VERCEL_SCOPE
    VERCEL_ALIAS: $DEV_VERCEL_ALIAS
    DOT_VERCEL: $DEV_VERCEL_PROJECT_JSON
    BRANCH_TARGET: develop

.staging_vars:
  variables:
    VERCEL_SCOPE: $STAGING_VERCEL_SCOPE
    VERCEL_ALIAS: $STAGING_VERCEL_ALIAS
    DOT_VERCEL: $STAGING_VERCEL_PROJECT_JSON
    BRANCH_TARGET: staging

.prod_vars:
  variables:
    VERCEL_SCOPE: $PROD_VERCEL_SCOPE
    VERCEL_ALIAS: $PROD_VERCEL_ALIAS
    DOT_VERCEL: $PROD_VERCEL_PROJECT_JSON
    BRANCH_TARGET: master
